return {
  colors = {
    background = '#1e1e2e',  -- base
    foreground = '#cdd6f4',   -- text
    cursor_bg = '#f5e0dc',    -- rosewater
    cursor_border = '#f5e0dc', -- rosewater
    cursor_fg = '#1e1e2e',    -- base

    ansi = {
      '#45475a',  -- surface1
      '#f38ba8',  -- red
      '#a6e3a1',  -- green
      '#f9e2af',  -- yellow
      '#89b4fa',  -- blue
      '#f5c2e7',  -- pink
      '#94e2d5',  -- teal
      '#bac2de',  -- subtext1
    },

    brights = {
      '#585b70',  -- surface2
      '#f38ba8',  -- red
      '#a6e3a1',  -- green
      '#f9e2af',  -- yellow
      '#89b4fa',  -- blue
      '#f5c2e7',  -- pink
      '#94e2d5',  -- teal
      '#a6adc8',  -- subtext0
    },
  },

  tab_bar = {
    background = "#181825",  -- mantle

    active_tab = {
      bg_color = '#1e1e2e',  -- base
      fg_color = '#cdd6f4',  -- text
      intensity = 'Normal',
      italic = false,
      strikethrough = false,
      underline = 'None',
    },

    inactive_tab = {
      bg_color = '#181825',  -- mantle
      fg_color = '#cdd6f4',  -- text
      intensity = 'Normal',
      italic = false,
      strikethrough = false,
      underline = 'None',
    },

    new_tab = {
      bg_color = '#181825',  -- mantle
      fg_color = '#cdd6f4',  -- text
      intensity = 'Normal',
      italic = false,
      strikethrough = false,
      underline = 'None',
    },
  },

  metadata = {
    name = 'Catppuccin Mocha',
    origin_url = 'https://github.com/catppuccin/catppuccin',
  },
}
