{
  config,
  pkgs,
  inputs,
  ...
}: {
  home.packages = with pkgs; [
    nitch
    #rustup
    github-cli
    neovide
    inputs.zen-browser.packages."${pkgs.system}".default
    inputs.nyxexprs.packages.${pkgs.system}.ani-cli
    inputs.ags.packages.${pkgs.system}.agsFull
    yazi
    wezterm
    microfetch
    gpu-screen-recorder
    hyprpanel
    libqalculate
    libdbusmenu-gtk3
    dbus-glib
    mangal
    mangareader
    tmux
    gtk4 
    komikku
  ];
}
